GET https://flashbackapi-uat.herokuapp.com/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxMTQzNTI2NzEyMTQ5MjAzMDI5MDMiLCJpYXQiOjE2MjYyODQ1MzQsImlzcyI6Imh0dHBzOi8vZ2l0aHViLmNvbS9qb25hc3JvdXNzZWwvanNvbndlYnRva2VuIn0.IF06hG19Fkv6hj3znitj-6eecaRXEz6EKXKtVj5_oVo

###
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBLZ2tzQmRpQlBlR2w2ZEhhck5mSlgzbm14RTMiLCJpYXQiOjE2MjI4MTgwODAsImlzcyI6Imh0dHBzOi8vZ2l0aHViLmNvbS9qb25hc3JvdXNzZWwvanNvbndlYnRva2VuIn0.adkBWK8rjk1-rbe5JbCaHw4ODFBGZV5UT1jnTNk1VoQ
