GET https://flashbackapi-uat.herokuapp.com/cardsetforowner
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxMTQzNTI2NzEyMTQ5MjAzMDI5MDMiLCJpYXQiOjE2MjI4MzcwMDUsImlzcyI6Imh0dHBzOi8vZ2l0aHViLmNvbS9qb25hc3JvdXNzZWwvanNvbndlYnRva2VuIn0.4R40jpvt7WTduBb13OPLtDZDBanP0N54rqo9wp7LmDU


eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBLZ2tzQmRpQlBlR2w2ZEhhck5mSlgzbm14RTMiLCJpYXQiOjE2MjI4MTgwODAsImlzcyI6Imh0dHBzOi8vZ2l0aHViLmNvbS9qb25hc3JvdXNzZWwvanNvbndlYnRva2VuIn0.adkBWK8rjk1-rbe5JbCaHw4ODFBGZV5UT1jnTNk1VoQ
